version: '3.8'

services:
  # memessenger:
  #   image: golang
  #   restart: always
  #   container_name: "meme"
  #   # build: .
  #   # command: ./wait-for-postgres.sh db ./memessenger
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_PASSWORD=postgrespw
  #   volumes:
  #     - ./:/appdata
  #   command: ["go", "run", "./appdata/cmd/main.go"]


  db:
    container_name: "db" 
    image: postgres:latest
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    expose:
      - "5432"
    command: -p 5432
    networks:
      - back
    environment:
       POSTGRES_PASSWORD: "postgrespw"
       POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: "pgadmin" 

    image: dpage/pgadmin4:5.1
    restart: always
    ports:
      - 80:80
    networks:
    - back
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  dbdata: 
  app: 


networks:
      back: